In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
from sklearn. preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler, MultiLabelBinarizer
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [6]:
fileloca_train = "~/GitFolders/ESRES/data_sets/samleData_vectoroutput.csv"

In [7]:
dataset_train = pd.read_csv(fileloca_train)

In [8]:
dataset_train_values = dataset_train.values

In [9]:
feature_names = list(dataset_train.columns[:11])
measure_names = list(dataset_train.columns[11:])
measure_names

['Too many people',
 'Change the lighting',
 'people to often in room',
 'transmission',
 'fans']

In [18]:
X = dataset_train_values[:, :11]
y = dataset_train_values[:, 11:]
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0.

In [34]:
unique_rows = np.unique(y, axis=0)
unique_rows





##### hier bin ich gerade #####

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0.]])

MultiLabelBinarizer()

In [7]:
scaler = MinMaxScaler(feature_range=(0, 1))
X_scaled = scaler.fit_transform(X)
Y_scaled = scaler.fit_transform(y)

In [8]:
train_samples, train_labels = shuffle(X_scaled, Y_scaled)

In [9]:
X_train, X_val, Y_train, Y_val = train_test_split(
    train_samples, train_labels, test_size=0.1, random_state=2
)

In [10]:
n_features = X.shape[1]
n_classes = y.shape[1]
n_classes = 7

In [11]:
def create_custom_model(input_dim, output_dim, nodes, n=2, name='model'):
    def create_model():
        # Create model
        model = Sequential(name=name)
        for i in range(n):
            model.add(Dense(nodes, input_dim=input_dim, activation='relu'))
        model.add(Dense(output_dim, activation='softmax'))

        # Compile model
        model.compile(Adam(lr=0.001), loss='categorical_crossentropy',
                      metrics=['accuracy'])
        return model

    return create_model

In [12]:
models = [create_custom_model(n_features, n_classes, 10, n=i, name='model_{}'.format(i))
              for i in range(2, 3)]

In [13]:
for create_model in models:
        create_model().summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                120       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 7)                 77        
Total params: 307
Trainable params: 307
Non-trainable params: 0
_________________________________________________________________


In [14]:

    for create_model in models:
        model = create_model()
        print('Model name:', model.name)
        # history_callback =\
        model.fit(X_train, Y_train,
                  batch_size=1,
                  epochs=100,
                  # verbose=0,
                  validation_data=(X_val, Y_val)
                  )


Model name: model_2
Epoch 1/100


ValueError: in user code:

    /home/mubuntu/anaconda3/envs/ESRES/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    /home/mubuntu/anaconda3/envs/ESRES/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/mubuntu/anaconda3/envs/ESRES/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/mubuntu/anaconda3/envs/ESRES/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/mubuntu/anaconda3/envs/ESRES/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:532 train_step  **
        loss = self.compiled_loss(
    /home/mubuntu/anaconda3/envs/ESRES/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:205 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    /home/mubuntu/anaconda3/envs/ESRES/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:143 __call__
        losses = self.call(y_true, y_pred)
    /home/mubuntu/anaconda3/envs/ESRES/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:246 call
        return self.fn(y_true, y_pred, **self._fn_kwargs)
    /home/mubuntu/anaconda3/envs/ESRES/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:1527 categorical_crossentropy
        return K.categorical_crossentropy(y_true, y_pred, from_logits=from_logits)
    /home/mubuntu/anaconda3/envs/ESRES/lib/python3.8/site-packages/tensorflow/python/keras/backend.py:4561 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    /home/mubuntu/anaconda3/envs/ESRES/lib/python3.8/site-packages/tensorflow/python/framework/tensor_shape.py:1117 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (1, 5) and (1, 7) are incompatible


In [3]:
mlb = MultiLabelBinarizer()
mlb.fit_transform([(1, 2), (3,)])
mlb



MultiLabelBinarizer()

In [4]:
mlb.classes_



array([1, 2, 3])